server:
  port: 8084

# Enables Eureka Registering
#spring:
#  application:
#    name: eventors

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#Fault Tolerance Support
#resilience4J:
#  retry:
#    instances:
#      eventlist:
#        max-attempts: 2
#        way-duration: 3s

security:
  oauth2:
    client:
      clientId: microclient
      clientSecret: secret
    resource:
      jwt:
        key-uri: http://localhost:8081/auth/oauth/token_key

