server:
  port: 8084
  servlet:
    context-path: /
    session:
      cookie:
        path: /
  ssl:
    key-store: classpath:eventorsstore.p12
    key-store-password: ${resourcepass}
    key-store-type: PKCS12
    key-alias: resourceserver
  error:
    whitelabel:
      enabled: false

# Enables Eureka Registering
#spring:
#  application:
#    name: eventors

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#Fault Tolerance Support
#resilience4J:
#  retry:
#    instances:
#      eventlist:
#        max-attempts: 2
#        way-duration: 3s

security:
  require-ssl: true
  oauth2:
    client:
      clientId: microclient
      clientSecret: secret
    resource:
      jwt:
        key-uri: ${EVENTOAS_HOST}/auth/oauth/token_key
        #key-uri: https://localhost:8081/auth/oauth/token_key

